SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `certifications` MODIFY `id` BIGINT(20) AUTO_INCREMENT;

INSERT INTO `certifications` (`title`) VALUES
  ('Advanced Level Linux Certification (LPIC-2)'),
  ('Agile Advanced Practitioner'),
  ('Agile Foundation'),
  ('Agile Foundation Certificate'),
  ('Agile Practitioner Certificate'),
  ('Agile Product Lifecycle Management 9 Certified Implementation Specialist'),
  ('Agile Project Management Certification – Foundation Level'),
  ('Agile Project Management Certification – Practicioner Level'),
  ('C Certified Professional Programmer – CLP'),
  ('C Certified Senior Programmer – CLS'),
  ('C Programming Language Certified Associate – CLA'),
  ('C++ Certified Associate Programmer – CPA'),
  ('C++ Certified Professional Programmer – CPP'),
  ('C++ Certified Senior Programmer – CPS'),
  ('Certificate of Cloud Seurity Knowledge (CCSK)'),
  ('Certificate on Cloud Architecture/Design'),
  ('Certificate on Cloud Technologies'),
  ('Certificate on Cloud/DevOps: Automating Cloud Infrastructure'),
  ('Certification in IT Asset Disposition (CITAD)'),
  ('​​​​Certified Advanced Windows Forensic Examiner (CAWFE)'),
  ('Certified Agile Tester'),
  ('Certified Application Security Specialist (CASS)'),
  ('Certified Associate Business Analyst (CABA)'),
  ('Certified Associate in Project Management (CAPM)'),
  ('Certified Associate in Software Quality (CASQ)'),
  ('Certified Associate in Software Testing (CAST)'),
  ('Certified Authorization Professional (CAP)'),
  ('Certified Big Data Architect'),
  ('Certified Big Data Consultant'),
  ('Certified Big Data Engineer'),
  ('Certified Big Data Professional'),
  ('Certified Big Data Science Professional'),
  ('Certified Big Data Scientist'),
  ('Certified Big Data Trainer'),
  ('Certified Big Governance Specialist'),
  ('Certified BIM Specialist'),
  ('Certified Biometrics Professional (CBP)'),
  ('Certified Business Architect (CBA)'),
  ('Certified Case Management Specialist (CCMS)'),
  ('Certified Cloud Architect'),
  ('Certified Cloud Architect (CCA)'),
  ('Certified Cloud Capacity Specialist'),
  ('Certified Cloud Governance Specialist'),
  ('Certified Cloud Professional (CCP)'),
  ('Certified Cloud Professional (CCP)'),
  ('Certified Cloud Security Specialist'),
  ('Certified Cloud Storage Specialist'),
  ('Certified Cloud Technology Professional'),
  ('Certified Cloud Trainer'),
  ('Certified Cloud Virtualization Specialist'),
  ('Certified Computer Examiner (CCE)'),
  ('Certified Computer Forensics Examiner (CCFE)'),
  ('Certified Computer Security Incident Handler (CSIH)'),
  ('Certified CPM Architect (CCA)'),
  ('Certified Data Centre Audit Professional (CDCAP)'),
  ('Certified Data Centre Design Professional (CDCDP)'),
  ('Certified Data Centre Energy Professional (CDCEP)'),
  ('Certified Data Centre Expert (CDCEMC)'),
  ('Certified Data Centre Facilities Operations Manager (CDFOM)'),
  ('Certified Data Centre Management Professional (CDCMP)'),
  ('Certified Data Centre Migration Specialist (CDMS)'),
  ('Certified Data Centre Professional (CDCP)'),
  ('Certified Data Centre Risk Professional (CDRP)'),
  ('Certified Data Centre Specialist (CDCS)'),
  ('Certified Data Centre Technician Professional (CDCTP)'),
  ('Certified Data Recovery Professional (CDRP)'),
  ('Certified Decision Management Architect (CDA)'),
  ('Certified DIACAP Assurance Enginner (CDAE)'),
  ('Certified Digital Forensics Examiner (C)DFE)'),
  ('Certified Disaster Recovery Engineer (C)DRE)'),
  ('Certified Ethical Hacker (CEH)'),
  ('Certified Expert Penetration Tester (CEPT)'),
  ('Certified Forensic Computer Examiner (CFCE)'),
  ('Certified Function Point Specialist (CFPS)'),
  ('Certified Hardware Asset Management Professional (CHAMP)'),
  ('Certified Identity Protection Advisor (CIPA)'),
  ('Certified Identity Risk Manager (CIRM)'),
  ('Certified in Risk and Information Systems Control (CRISC)'),
  ('Certified in the Governance of Enterprise IT (CGEIT)'),
  ('Certified Incident Handling Engineer (C)IHE)'),
  ('Certified Infoblox Core Administrator (CICA)'),
  ('Certified Infoblox Core Engineer (CICE)'),
  ('Certified Infoblox NetMRI Administrator (CINA)'),
  ('Certified Infoblox Support Technician (CIST)'),
  ('Certified Information Professional (CIP)'),
  ('Certified Information Security Manager (CISM)'),
  ('Certified Information Systems Auditor (CISA)'),
  ('Certified Information Systems Security Officer (C)ISSO)'),
  ('Certified Information Systems Security Professional (CISSP)'),
  ('Certified Information Systems Security Professional Architecture (CISSP-ISSAP)'),
  ('Certified Information Systems Security Professional Engineering (CISSP-ISSEP)'),
  ('Certified Information Systems Security Professional Management (CISSP-ISSMP)'),
  ('Certified Information Technology Manager (CITM)'),
  ('Certified Integration Specialist (CIS)'),
  ('Certified IT Asset Manager (CITAM)'),
  ('Certified Lead System Architect (CLSA)'),
  ('Certified Manager of Software Quality (CMSQ)'),
  ('Certified Manager of Software Testing (CMST)'),
  ('Certified Mobile Asset Manager (CMAM)'),
  ('Certified NetIQ Identity Manager Administrator'),
  ('Certified Network Cable Installer (CNCI)'),
  ('Certified Network Cable Installer (CNCI) Copper Cabling'),
  ('Certified Network Cable Installer (CNCI) Fibre Optic Cabling'),
  ('Certified Network Computer Technician (CNCT)'),
  ('Certified Network Defense Architect (CNDA)'),
  ('Certified Network Forensics Examiner (C)NFE)'),
  ('Certified Network Infrastructure Technician (CNIT)'),
  ('Certified Network Security Engineer (CNSE)'),
  ('Certified Network Systems Technician (CNST)'),
  ('Certified Next-Best-Action Consultant (CNC)'),
  ('Certified Novell Administrator (CNA)'),
  ('Certified Novell Engineer (CNE)'),
  ('Certified Novell Instructor (CNI)'),
  ('Certified Novell ZENworks Administrator'),
  ('Certified Nutanix Platform Professional (NPP)'),
  ('Certified Nutanix Platform Sales (NPS)'),
  ('Certified Nutanix Platform Sales Engineer (NPSE)'),
  ('Certified Penetration Tester (CPT)'),
  ('Certified Penetration Testing Consultant (C)PTC)'),
  ('Certified Penetration Testing Engineer (C)PTE)'),
  ('Certified Professional in Electronic Health Records (CPEHR)'),
  ('Certified Professional in Health Information Exchange (CPHIE)'),
  ('Certified Professional in Health Information Technology (CPHIT)'),
  ('Certified Professional in Operating Rules Administration (CPORA)'),
  ('Certified Quantitative Software Process Engineer (CQSPE)'),
  ('Certified Records Manager (CRM)'),
  ('Certified Red Flag Specialist (CRFS)'),
  ('Certified Reporting Specialist (CRS)'),
  ('Certified Reverse Engineering Analyst (CREA)'),
  ('Certified SCADA Security Architect (CSSA)'),
  ('Certified Scrum Coach'),
  ('Certified Scrum Developer'),
  ('Certified Scrum Master'),
  ('Certified Scrum Product Owner'),
  ('Certified Scrum Professional'),
  ('Certified Scrum Trainer'),
  ('Certified Secure Computer User (CSCU)'),
  ('Certified Secure Linux Engineer (C)SLE)'),
  ('Certified Secure Software Lifecycle Professional (CSSLP)'),
  ('Certified Secure Web Applications Engineer (C)SWAE)'),
  ('Certified Security Leadership Officer (C)SLO)'),
  ('Certified Security Sentinel (C)SS)'),
  ('Certified Senior Next-Best-Action Consultant (CSNC)'),
  ('Certified Senior System Architect (CSSA)'),
  ('Certified SOA .NET Developer'),
  ('Certified SOA Analyst'),
  ('Certified SOA Architect'),
  ('Certified SOA Consultant'),
  ('Certified SOA Governance Specialist'),
  ('Certified SOA Java Developer'),
  ('Certified SOA Professional (SOACP)'),
  ('Certified SOA QA Specialist'),
  ('Certified SOA Security Specialist'),
  ('Certified SOA Trainer'),
  ('Certified Software Asset Management (CSAM)'),
  ('Certified Software Business Analyst (CSBA)'),
  ('Certified Software Development Associate (CSDA)'),
  ('Certified Software Development Professional (CSDP)'),
  ('Certified Software Process Engineer (CSPE)'),
  ('Certified Software Project Manager (CSPM)'),
  ('Certified Software Quality Analyst (CSQA)'),
  ('Certified Software Test Analyst (CSTA)'),
  ('Certified Software Tester (CST)'),
  ('Certified SonicWALL Sales Representative (CSSR)'),
  ('Certified SonicWALL Security Administrator (CSSA)'),
  ('Certified SonicWALL Trainer (CST)'),
  ('Certified Spring Enterprise Integration Specialist'),
  ('Certified Spring Professional'),
  ('Certified Spring Web Application Developer'),
  ('Certified System Administrator (CSA)'),
  ('Certified System Architect (CSA)'),
  ('Certified Technology Specialist (CTS)'),
  ('Certified Technology Specialist-Design (CTS-D)'),
  ('Certified Technology Specialist-Installation (CTS-I)'),
  ('Certified Telecommunications Project Management (CTPM)'),
  ('Certified Telecommunications Project Management (CTPM)'),
  ('Certified TIA-942 Design Consultant (CTDC)'),
  ('Certified TIA-942 Internal Auditor (CTIA)'),
  ('Certified TRITON DLP Olympian'),
  ('Certified TRITON Email Olympian Certified'),
  ('Certified TRITON Web Olympian'),
  ('Certified TYPO3 CMS Integrator'),
  ('Certified User Experience Specialist (CUXS)'),
  ('Certified Vulnerability Assessor (C)VA)'),
  ('Certified Web App Penetration Tester (CWAPT)'),
  ('Certified Windows Security Specialist (CWSS)'),
  ('Certified Wireless Analysis Professional (CWAP)'),
  ('Certified Wireless Design Professional (CWDP)'),
  ('Certified Wireless Network Administrator (CWNA)'),
  ('Certified Wireless Network Expert (CWNE)'),
  ('Certified Wireless Network Trainer (CWNT)'),
  ('Certified Wireless Security Engineer (C)WSE)'),
  ('Certified Wireless Security Professional (CWSP)'),
  ('Certified Wireless Technology Specialist (CWTS)'),
  ('Microsoft Certified Professional (MCP)'),
  ('Microsoft Certified Professional Developer (MCPD) Windows Phone Developer'),
  ('Microsoft Certified Solutions Associate (MCSA) Office 365'),
  ('Microsoft Certified Solutions Associate (MCSA) SQL Server'),
  ('Microsoft Certified Solutions Associate (MCSA) Windows 7'),
  ('Microsoft Certified Solutions Associate (MCSA) Windows 8'),
  ('Microsoft Certified Solutions Associate (MCSA) Windows Server 2008'),
  ('Microsoft Certified Solutions Associate (MCSA) Windows Server 2012'),
  ('Microsoft Certified Solutions Developer (MCSD) Application Lifecycle Management'),
  ('Microsoft Certified Solutions Developer (MCSD) SharePoint Applications'),
  ('Microsoft Certified Solutions Developer (MCSD) Web Applications'),
  ('Microsoft Certified Solutions Developer (MCSD) Windows Store Apps'),
  ('Microsoft Certified Solutions Expert (MCSE) Business Intelligence'),
  ('Microsoft Certified Solutions Expert (MCSE) Communication'),
  ('Microsoft Certified Solutions Expert (MCSE) Data Platform'),
  ('Microsoft Certified Solutions Expert (MCSE) Desktop Infrastructure'),
  ('Microsoft Certified Solutions Expert (MCSE) Messaging'),
  ('Microsoft Certified Solutions Expert (MCSE) Private Cloud'),
  ('Microsoft Certified Solutions Expert (MCSE) Server Infrastructure'),
  ('Microsoft Certified Solutions Expert (MCSE) SharePoint'),
  ('Microsoft Certified Specialist Developing Microsoft Azure Solution'),
  ('Microsoft Certified Specialist Implementing Microsoft Azure Infrastructure Solutions'),
  ('Microsoft Office Specialist (MOS) Master'),
  ('Microsoft Office Specialist (MOS) Microsoft Office Access 2013'),
  ('Microsoft Office Specialist (MOS) Microsoft Office Excel 2013'),
  ('Microsoft Office Specialist (MOS) Microsoft Office Excel 2013 Expert'),
  ('Microsoft Office Specialist (MOS) Microsoft Office OneNote 2013'),
  ('Microsoft Office Specialist (MOS) Microsoft Office Outlook 2013'),
  ('Microsoft Office Specialist (MOS) Microsoft Office PowerPoint 2013'),
  ('Microsoft Office Specialist (MOS) Microsoft Office Word 2013'),
  ('Microsoft Office Specialist (MOS) Microsoft Office Word 2013 Expert'),
  ('Microsoft Office Specialist (MOS) Microsoft SharePoint 2013'),
  ('Microsoft Operations Framework Foundation'),
  ('Microsoft Specialist certification in Lync 2013'),
  ('Microsoft Specialist certification in Microsoft Project 2013'),
  ('Microsoft Specialist certification in Office 365'),
  ('Microsoft Specialist certification in Server Virtualization'),
  ('Microsoft Specialist certification in Visual Studio'),
  ('Microsoft Specialist certification in Windows UX Design'),
  ('Microsoft Technology Associate (MTA) Database'),
  ('Microsoft Technology Associate (MTA) Developer'),
  ('Microsoft Technology Associate (MTA) IT Infrastructure'),
  ('MikroTik Certified Internetworking Engineer (MTCINE)'),
  ('MikroTik Certified Network Associate (MTCNA)'),
  ('MikroTik Certified Routing Engineer (MTCRE)'),
  ('MikroTik Certified Traffic Control Engineer (MTCTCE)'),
  ('MikroTik Certified User Management Engineer (MTCUME)'),
  ('MikroTik Certified Wireless Engineer (MTCWE)'),
  ('Mile2'),
  ('Mirantis'),
  ('Mobile Electronics Certified Professional'),
  ('NetApp Certified B & R Implementation Engineer (NCIE – B&R)'),
  ('NetApp Certified Data Administrator (NCDA)'),
  ('NetApp Certified SAN Implementation Engineer (NCIE – SAN)'),
  ('NetApp Certified Storage Associate (NCSA)'),
  ('NetScout'),
  ('nGenius Certified Expert (nCE)'),
  ('nGenius Certified Professional – CDMA 2000 (nCP-CDMA)'),
  ('nGenius Certified Professional – GSM Technologies (nCP-GSM)'),
  ('nGenius Certified Professional (nCP)'),
  ('Novell'),
  ('Novell Academic Instructor'),
  ('Novell Certified Administrator Enterprise Services (NCA ES)'),
  ('Novell Certified Engineer Enterprise Services (NCE ES)'),
  ('Nutanix'),
  ('OBASHI Certification'),
  ('Object Management Group (OMG)'),
  ('OESF Authorized Certification Engineer for Android (ACE)'),
  ('Offensive Security'),
  ('Offensive Security Certified Expert (OSCE)'),
  ('Offensive Security Certified Professional (OSCP)'),
  ('Offensive Security Exploitation Expert (OSEE)'),
  ('Offensive Security Web Expert (OSWE)'),
  ('Offensive Security Wireless Professional (OSWP)'),
  ('OMG-Certified Expert in BPM (OCEB) Business Intermediate'),
  ('OMG-Certified Expert in BPM (OCEB) Fundamental'),
  ('OMG-Certified Real-time and Embedded Systems Specialist (OCRES) Advanced'),
  ('OMG-Certified Real-time and Embedded Systems Specialist (OCRES) Fundamentals'),
  ('OMG-Certified Real-time and Embedded Systems Specialist (OCRES) Intermediate'),
  ('OMG-Certified Systems Modeling Professional (OCSMP) Model Builder – Advanced'),
  ('OMG-Certified Systems Modeling Professional (OCSMP) Model Builder – Fundamental'),
  ('OMG-Certified Systems Modeling Professional (OCSMP) Model Builder – Intermediate'),
  ('OMG-Certified Systems Modeling Professional (OCSMP) Model User'),
  ('OMG-Certified UML Professional (OCUP) Advanced'),
  ('OMG-Certified UML Professional (OCUP) Fundamental'),
  ('OMG-Certified UML Professional (OCUP) Intermediate'),
  ('Open Embedded Software Foundation'),
  ('Open FAIR Foundation'),
  ('OpenStack Administrator Certification Exam – Associate Level'),
  ('OpenStack Administrator Certification Exam – Professional Level'),
  ('OpenText Archive Server Certification (OTAS)'),
  ('OpenText Content Server Consultant Certification (OTCSBC)'),
  ('OpenText Content Server Developer Certification (OTCSSD)'),
  ('OpenText Content ServerAdministrator Certification (OTCSSA)'),
  ('OpenText ProVision 9.1 Business Architecture Certification'),
  ('Optical Communications Associate (OC-A)'),
  ('Optical Communications Professional (OC-P)'),
  ('Oracle Access Management Suite Plus 11g Certified Implementation Specialist'),
  ('Oracle Advanced Controls Applications 2014 Certified Implementation Specialist'),
  ('Oracle Advanced PL/SQL Developer Certified Professional'),
  ('Oracle Application Development Framework 11g Certified Implementation Specialist'),
  ('Oracle Application Development Framework 12c Certified Implementation Specialist'),
  ('Oracle Application Express Developer Certified Expert'),
  ('Oracle Application Grid 11g Certified Implementation Specialist'),
  ('Oracle Application Integration Architecture 11g Certified Implementation Specialist'),
  ('Oracle Argus Safety 7 Certified Implementation Specialist'),
  ('Oracle Argus Safety Suite 6 Certified Implementation Specialist'),
  ('Oracle ATG Web Commerce Suite 10 Implementation Developer Certified Implementation Specialist'),
  ('Oracle Business Intelligence Applications 7 for CRM Certified Implementation Specialist'),
  ('Oracle Business Intelligence Applications 7 for ERP Certified Implementation Specialist'),
  ('Oracle Business Intelligence Foundation 10 Certified Implementation Specialist'),
  ('Oracle Business Intelligence Foundation Suite 11g Certified Implementation Specialist'),
  ('Oracle Certified Associate, Java SE 5/SE 6'),
  ('Oracle Certified Associate, Java SE 7 Programmer'),
  ('Oracle Certified Associate, Java SE 8 Programmer'),
  ('Oracle Certified Associate, Oracle Linux 5 and 6 System Administrator'),
  ('Oracle Certified Associate, Oracle Solaris 10 Operating System'),
  ('Oracle Certified Associate, Oracle Solaris 11 System Administrator'),
  ('Oracle Certified Associate, Oracle WebLogic Server 11g System Administrator'),
  ('Oracle Certified Associate, Oracle WebLogic Server 12c Administrator'),
  ('Oracle Certified Expert, Java EE 6 Enterprise JavaBeans Developer'),
  ('Oracle Certified Expert, Java EE 6 Java Persistence API Developer'),
  ('Oracle Certified Expert, Java EE 6 JavaServer Faces Developer'),
  ('Oracle Certified Expert, Java EE 6 Web Component Developer'),
  ('Oracle Certified Expert, Java EE 6 Web Services Developer'),
  ('Oracle Certified Expert, Oracle Database 11g Release 2 SQL Tuning'),
  ('Oracle Certified Expert, Oracle Exadata X3 and X4 Administrator'),
  ('Oracle Certified Expert, Oracle Real Application Clusters 11g and Grid Infrastructure Administrator'),
  ('Oracle Certified Expert, Oracle Solaris 10 Network Administrator'),
  ('Oracle Certified Expert, Oracle Solaris 10 Security Administrator'),
  ('Oracle Certified Expert, Siebel Customer Relationship Management 8 Business Analyst'),
  ('Oracle Certified Master, Database Cloud Administrator'),
  ('Oracle Certified Master, Java EE 5 Enterprise Architect'),
  ('Oracle Certified Master, Java EE 6 Enterprise Architect'),
  ('Oracle Certified Master, Java SE 6 Developer'),
  ('Oracle Certified Professional, Database Cloud Administrator'),
  ('Oracle Certified Professional, Java EE 5 Business Component Developer'),
  ('Oracle Certified Professional, Java EE 5 Web Component Developer'),
  ('Oracle Certified Professional, Java EE 5 Web Services Developer'),
  ('Oracle Certified Professional, Java ME 1 Mobile Application Developer'),
  ('Oracle Certified Professional, Java SE 5 Programmer'),
  ('Oracle Certified Professional, Java SE 6 Programmer'),
  ('Oracle Certified Professional, Java SE 7 Programmer'),
  ('Oracle Certified Professional, MySQL 5.6 Database Administrator'),
  ('Oracle Certified Professional, MySQL 5.6 Developer'),
  ('Oracle Certified Professional, Oracle Fusion Middleware 11g Forms Developer'),
  ('Oracle Certified Professional, Oracle Linux 6 System Administrator'),
  ('Oracle Certified Professional, Oracle Solaris 10 System Administrator'),
  ('Oracle Certified Professional, Oracle Solaris 11 System Administrator'),
  ('Oracle Certified Professional, Oracle Solaris Cluster 3.2 System Administrator'),
  ('Oracle Cloud Application Foundation Certified Implementation Specialist'),
  ('Oracle Communications Billing and Revenue Management 7 Advanced Certified Implementation Specialist'),
  ('Oracle Communications Billing and Revenue Management 7 Basic Certified Implementation Specialist'),
  ('Oracle Communications Converged Application Server 5 Certified Implementation Specialist'),
  ('Oracle Communications Order and Service Management Server 7 Certified Implementation Specialist'),
  ('Oracle Communications Services Gatekeeper 5 Certified Implementation Specialist'),
  ('Oracle Communications Session Border Controller Certified Implementation Specialist'),
  ('Oracle Communications Unified Communications Suite 7 Certified Implementation Specialist'),
  ('Oracle Communications WebRTC Session Controller 7 Certified Implementation Specialist'),
  ('Oracle CRM On Demand Certified Implementation Specialist'),
  ('Oracle Customer Hub and Oracle Data Quality Certified Implementation Specialist'),
  ('Oracle Data Integrator 11g Certified Implementation Specialist'),
  ('Oracle Data Warehousing 11g Certified Implementation Specialist'),
  ('Oracle Database 10g Administrator Certified Associate'),
  ('Oracle Database 10g Administrator Certified Master'),
  ('Oracle Database 10g Administrator Certified Professional'),
  ('Oracle Database 10g Managing Oracle on Linux Certified Expert'),
  ('Oracle Database 10g Real Applications Clusters Administrator Certified Expert'),
  ('Oracle Database 11g Administrator Certified Associate'),
  ('Oracle Database 11g Administrator Certified Master'),
  ('Oracle Database 11g Administrator Certified Professional'),
  ('Oracle Database 11g Certified Implementation Specialist'),
  ('Oracle Database 11g Performance Tuning Certified Expert'),
  ('Oracle Database 11g Security Certified Implementation Specialist'),
  ('Oracle Database 12c Administrator Certified Associate'),
  ('Oracle Database 12c Administrator Certified Professional'),
  ('Oracle Database 12c Certified Implementation Specialist'),
  ('Oracle Database Performance and Tuning 2015 Certified Implementation Specialist'),
  ('Oracle Database SQL Certified Expert'),
  ('Oracle Documaker Standard Edition 12 Certified Implementation Specialist'),
  ('Oracle E-Business Suite 12 Financial Management Certified Implementation Specialist: Oracle General Ledger'),
  ('Oracle E-Business Suite 12 Financial Management Certified Implementation Specialist: Oracle Payables'),
  ('Oracle E-Business Suite 12 Financial Management Certified Implementation Specialist: Oracle Receivables'),
  ('Oracle E-Business Suite 12 Supply Chain Certified Implementation Specialist: Oracle Inventory'),
  ('Oracle E-Business Suite 12 Supply Chain Certified Implementation Specialist: Oracle Order Management'),
  ('Oracle E-Business Suite 12 Supply Chain Certified Implementation Specialist: Oracle Purchasing'),
  ('Oracle E-Business Suite R12 Advanced Supply Chain Planning Consultant Certified Expert'),
  ('Oracle E-Business Suite R12 Applications Database Administrator Certified Professional'),
  ('Oracle E-Business Suite R12 Human Capital Management Certified Implementation Specialist'),
  ('Oracle E-Business Suite R12 Project Certified Implementation Specialist'),
  ('Oracle Eloqua Marketing Cloud Service 2013 Certified Implementation Specialist'),
  ('Oracle Endeca Commerce 3.1 Implementation Developer Certified Implementation Specialist'),
  ('Oracle Endeca Information Discovery 2.3 Certified Implementation Specialist'),
  ('Oracle Endeca Information Discovery 3.1 Certified Implementation Specialist'),
  ('Oracle Enterprise Manager 11g Application Quality Management Certified Implementation Specialist'),
  ('Oracle Enterprise Manager 11g Certified Implementation Specialist'),
  ('Oracle Enterprise Manager 12c Certified Implementation Specialist'),
  ('Oracle Enterprise Taxation and Policy Management 2 Certified Implementation Specialist'),
  ('Oracle Enterprise Taxation Management 2 Certified Implementation Specialist'),
  ('Oracle Essbase 11 Certified Implementation Specialist'),
  ('Oracle Exadata Database Machine 2014 Certified Implementation Specialist'),
  ('Oracle Exalogic Elastic Cloud 2014 Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Direct Banking 12 Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Direct Banking 6 Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Islamic Banking 12 Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Universal Banking 11 Basic Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Universal Banking 11 Technical Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Universal Banking 11 Trade Finance Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Universal Banking 12 Advanced Functional Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Universal Banking 12 Core Functional Certified Implementation Specialist'),
  ('Oracle FLEXCUBE Universal Banking 12 Technical Certified Implementation Specialist'),
  ('Oracle Forms Developer Certified Professional'),
  ('Oracle Fusion CRM: Sales 11g Certified Implementation Specialist'),
  ('Oracle Fusion CRM: Sales 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Distributed Order Orchestration 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Financials 11g Accounts Payable Certified Implementation Specialist'),
  ('Oracle Fusion Financials 11g Accounts Receivable Certified Implementation Specialist'),
  ('Oracle Fusion Financials 11g General Ledger Certified Implementation Specialist'),
  ('Oracle Fusion Financials: Accounts Payable 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Financials: Accounts Receivable 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Financials: General Ledger 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Global Human Resources 2014 Certified Implementation Specialist'),
  ('Oracle Fusion HCM: Talent Management 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Human Capital Management 11g Human Resources Certified Implementation Specialist'),
  ('Oracle Fusion Human Capital Management 11g Talent Management Certified Implementation Specialist'),
  ('Oracle Fusion Incentive Compensation 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Procurement 2014 Certified Implementation Specialist'),
  ('Oracle Fusion Project Portfolio Management 2014 Certified Implementation Specialist'),
  ('Oracle Global Trade Management 6 Certified Implementation Specialist'),
  ('Oracle GoldenGate 10 Certified Implementation Specialist'),
  ('Oracle GoldenGate 11g Certified Implementation Specialist'),
  ('Oracle Hyperion Data Relationship Management Certified Implementation Specialist'),
  ('Oracle Hyperion Financial Management 11 Certified Implementation Specialist'),
  ('Oracle Hyperion Planning 11 Certified Implementation Specialist'),
  ('Oracle Identity Governance Suite 11g Certified Implementation Specialist'),
  ('Oracle Insurance Policy Administration 9 Certified Implementation Specialist'),
  ('Oracle Internet Application Developer Certified Professional, Oracle Forms Developer Release 6/6i'),
  ('Oracle iStore 12 Certified Implementation Specialist'),
  ('Oracle IT Architecture BPM 2013 Certified Architecture Specialist'),
  ('Oracle IT Architecture Release 3 Certified Architecture Specialist'),
  ('Oracle IT Architecture SOA 2013 Certified Architecture Specialist'),
  ('Oracle Life Sciences Data Hub 2 Certified Implementation Specialist'),
  ('Oracle Linux 6 Certified Implementation Specialist'),
  ('Oracle Linux Certified Implementation Specialist'),
  ('Oracle PL/SQL Developer Certified Associate'),
  ('Oracle Policy Automation 10 Certified Implementation Specialist'),
  ('Oracle Real Application Clusters 11g Certified Implementation Specialist'),
  ('Oracle Real Application Clusters 12c Certified Implementation Specialist'),
  ('Oracle Retail Demand Forecasting 13.3 Functional Implementer Certified Implementation Specialist'),
  ('Oracle Retail Integration Bus 13.2 Certified Implementation Specialist'),
  ('Oracle Retail Merchandise Planning and Optimization 13.3 Certified Implementation Specialist'),
  ('Oracle Retail Merchandising System 13.2 Foundation Functional Implementer Certified Implementation Specialist'),
  ('Oracle Retail Point-of-Service Certified Implementation Specialist'),
  ('Oracle Retail Predictive Application Server 13 Certified Implementation Specialist'),
  ('Oracle Retail Price Management 13.2 Functional Implementer Certified Implementation Specialist'),
  ('Oracle Retail Store Inventory Management 13.2 Functional Implementer Certified Implementation Specialist'),
  ('Oracle RightNow CX Cloud Service 2012 Certified Implementation Specialist'),
  ('Oracle RightNow CX Cloud Service 2012 Certified Implementation Specialist'),
  ('Oracle SOA Suite 11g Certified Implementation Specialist'),
  ('Oracle Social Relationship Management Cloud Service 2014 Certified Implementation Specialist'),
  ('Oracle Solaris 11 Installation and Configuration Certified Implementation Specialist'),
  ('Oracle Spatial 11g Certified Implementation Specialist'),
  ('Oracle Taleo Recruiting Cloud Service 2013 Certified Implementation Specialist'),
  ('Oracle Transportation Management 6 Certified Implementation Specialist'),
  ('Oracle Unified Business Process Management Suite 11g Certified Implementation Specialist'),
  ('Oracle Unified Method 5 Certified Implementation Specialist'),
  ('Oracle User Productivity Kit 11 Certified Implementation Specialist'),
  ('Oracle User Productivity Kit 11 Technical Consultant Certified Implementation Specialist'),
  ('Oracle Utilities Customer Care and Billing 2 Certified Implementation Specialist'),
  ('Oracle Utilities Meter Data Management 2 Certified Implementation Specialist'),
  ('Oracle Utilities Mobile Workforce Management 2 Certified Implementation Specialist'),
  ('Oracle Utilities Smart Grid Gateway 2 for Advanced Metering Infrastructure Certified Implementation Specialist'),
  ('Oracle Value Chain Planning: Demantra Demand Management 7 Certified Implementation Specialist'),
  ('Oracle Virtual Desktop Infrastructure 3 Certified Implementation Specialist'),
  ('Oracle VM 2.0 for x86 Certified Implementation Specialist'),
  ('Oracle VM 3.0 for x86 Certified Implementation Specialist'),
  ('Oracle WebCenter Content 11g Certified Implementation Specialist'),
  ('Oracle WebCenter Portal 11g Certified Implementation Specialist'),
  ('Oracle WebCenter Sites 11g Certified Implementation Specialist'),
  ('Oracle WebLogic Server 12c Certified Implementation Specialist'),
  ('Oracle ZFS Storage ZS3 Certified Implementation Specialist'),
  ('Oracle9i Database Administrator Certified Professional'),
  ('Professional Cloud Administrator'),
  ('Professional Cloud Developer'),
  ('Professional Cloud Security Manager'),
  ('Professional Cloud Service Manager'),
  ('Professional Cloud Solutions Architect'),
  ('Professional Control of IT Services according to ISO/IEC'),
  ('Professional Scrum Developer'),
  ('Professional Scrum Foundations'),
  ('Professional Scrum Master'),
  ('Professional Scrum Product Owner'),
  ('Professional Support of IT Services according to ISO/IEC'),
  ('Red Hat Certificate of Expertise in Camel Development'),
  ('Red Hat Certificate of Expertise in Clustering and Storage Management'),
  ('Red Hat Certificate of Expertise in Deployment and Systems Management'),
  ('Red Hat Certificate of Expertise in ESB'),
  ('Red Hat Certificate of Expertise in Hybrid Cloud Storage'),
  ('Red Hat Certificate of Expertise in Performance Tuning'),
  ('Red Hat Certificate of Expertise in Persistence'),
  ('Red Hat Certificate of Expertise in Platform-as-a-Service'),
  ('Red Hat Certificate of Expertise in Server Hardening'),
  ('Red Hat Certified Architect (RHCA)'),
  ('Red Hat Certified Engineer (RHCE)'),
  ('Red Hat Certified JBoss Administrator (RHCJA)'),
  ('Red Hat Certified JBoss Administrator (RHCJA)'),
  ('Red Hat Certified JBoss Developer(RHCJD)'),
  ('Red Hat Certified System Administrator (RHCSA)'),
  ('Red Hat Certified System Administrator in Red Hat OpenStack'),
  ('Red Hat Certified Virtualization Administrator (RHCVA)'),
  ('VMware Certified Advanced Professional – Cloud Infrastructure Administration (VCAP-CIA)'),
  ('VMware Certified Advanced Professional – Cloud Infrastructure Design (VCAP-CID)'),
  ('VMware Certified Advanced Professional – Data Center Administration (VCAP-DCA)'),
  ('VMware Certified Advanced Professional – Data Center Design (VCAP-DCD)'),
  ('VMware Certified Advanced Professional – Desktop Administration (VCAP-DTA)'),
  ('VMware Certified Advanced Professional – Desktop Design (VCAP-DTD)'),
  ('VMware Certified Associate – Cloud (VCA-Cloud)'),
  ('VMware Certified Associate – Data Center Virtualization (VCA-DCV)'),
  ('VMware Certified Associate – Workforce Mobility (VCA-WM)'),
  ('VMware Certified Design Expert – Cloud (VCDX-Cloud)'),
  ('VMware Certified Design Expert – Data Center Virtualization (VCDX-DCV)'),
  ('VMware Certified Design Expert – Network Virtualization (VCDX-NV)'),
  ('VMware Certified Design Expert-Desktop (VCDX-DT)'),
  ('VMware Certified Professional – Cloud (VCP-Cloud)'),
  ('VMware Certified Professional – Data Center Virtualization (VCP-DCV)'),
  ('VMware Certified Professional – Desktop (VCP-DT)'),
  ('VMware Certified Professional – Network Virtualization (VCP-NV)'),
  ('VMware Certified Professional – Network Virtualization (VCP-NV)');
